/////// Posts ///////

### Get All posts
GET http://localhost:3000/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA

### Get Post By Id
GET http://localhost:3000/posts/67cc86e8d5e638008887cf8f
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA

### Get Posts By Sender
GET http://localhost:3000/posts?sender=67cc8485f5d54670427842c5
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA


### DELETE post
DELETE http://localhost:3000/posts/67cc86e8d5e638008887cf8f
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA

### Create Post
POST http://localhost:3000/posts
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NmMGYyNDQxODYxNGM4NDljOTc0MzEiLCJyYW5kb20iOiIwLjM2ODI0NTk1MzA1MTE1NTA0IiwiaWF0IjoxNzQxNjIzMDg0LCJleHAiOjE3NDIyMjc4ODR9.pl8l-qzcCrLeYpxTPEmX32j9y8rWBJbe6ussDXvkisk
Content-Type: application/json

{
"content": "The night recedes as I prepare to journey toward dawn, towarddreamscapes of memory. Flashes of light across time and place illuminating a run to the ocean and the sound of waves crashing and the tidal repetition of my name being called. Here, before the sound of people racing to an uncertain life, I hear moments in the darkness before the eastern glow lightens dark blue and then finally light blue and the sky and morning star confirm that up until this moment this life has not been a dream and it was true that I’ve seen blossoms fall gently from cherry trees at the slightest change in the sacred wind frozen in time counting the cadence of my footsteps on the graveled path and the sound of my sacred breath, my prayer that other darker memories remain hidden in the night of my soul to be discovered when the morning whispers to me Now you can journey inward to find the child who cowers in fear from lightning and thunder and belts and closed fists"
}

### Update Post
PUT http://localhost:3000/posts/67cc84d1f5d54670427842c9
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA
Content-Type: application/json

{
  "content": "post liked update"
}


/////// Comments ///////

### Get All Comments
GET http://localhost:3000/comments
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1YzI0NzEzZDNiZWMwODA3ZTQ4M2IiLCJyYW5kb20iOiIwLjMyNzM0MjMxODMyNTExNDA3IiwiaWF0IjoxNzQxMDE2NjkwLCJleHAiOjE3NDE2MjE0OTB9.H4CgkF12Jx9GmN-5l1SUG-UeVtpuzTACuEnTIgcBhos

### Get All Comments Of A Post ( By PostId )
GET http://localhost:3000/comments?postId=678f76824804fbb8a1bb826b
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1YzI0NzEzZDNiZWMwODA3ZTQ4M2IiLCJyYW5kb20iOiIwLjMyNzM0MjMxODMyNTExNDA3IiwiaWF0IjoxNzQxMDE2NjkwLCJleHAiOjE3NDE2MjE0OTB9.H4CgkF12Jx9GmN-5l1SUG-UeVtpuzTACuEnTIgcBhos

### Get Comment By Id
GET http://localhost:3000/comments/67c5cf54686af915f4ca5ee8
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1YzI0NzEzZDNiZWMwODA3ZTQ4M2IiLCJyYW5kb20iOiIwLjMyNzM0MjMxODMyNTExNDA3IiwiaWF0IjoxNzQxMDE2NjkwLCJleHAiOjE3NDE2MjE0OTB9.H4CgkF12Jx9GmN-5l1SUG-UeVtpuzTACuEnTIgcBhos

### Create Comment
POST http://localhost:3000/comments
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MTA2ZTkyNWZiNmNmZTA5ZTM0YWMiLCJyYW5kb20iOiIwLjk3ODkzNDUxMTE2NzEwMDYiLCJpYXQiOjE3NDExNjY2NjEsImV4cCI6MTc0MTc3MTQ2MX0.kkZKCQodDGYVUz8sp-0vj-sLaNpyHBUThpsn31JCiwk
Content-Type: application/json

{
  "postId": "67c8187185aff2e7604bad55",
  "content": "why not"
}

### Delete Comment

DELETE http://localhost:3000/comments/67c818ec85aff2e7604bad5c
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MTA2ZTkyNWZiNmNmZTA5ZTM0YWMiLCJyYW5kb20iOiIwLjk3ODkzNDUxMTE2NzEwMDYiLCJpYXQiOjE3NDExNjY2NjEsImV4cCI6MTc0MTc3MTQ2MX0.kkZKCQodDGYVUz8sp-0vj-sLaNpyHBUThpsn31JCiwk

### Update Comment

PUT http://localhost:3000/comments/67c81258bbfb9ea8790e33ba
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MTA2ZTkyNWZiNmNmZTA5ZTM0YWMiLCJyYW5kb20iOiIwLjQ0ODkxNjExOTU2OTIwNDYzIiwiaWF0IjoxNzQxMTY1MDk2LCJleHAiOjE3NDE3Njk4OTZ9.RsfV9IajUSSDF8oVJN54ApuNE-L15--WKzxgMI3g9Jc
Content-Type: application/json

{
  "content": "Great picture??????????"
}

/////// Users ///////

### Register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "userName": "yaeli",
  "email": "yaeli@gmail",
  "password": "123"
}

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "yaeli@gmail",
  "password": "123"
}

### Logout

GET http://localhost:3000/users/me
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2QwYTM2MDAxYzcwNDFmN2JjMjBlNGEiLCJyYW5kb20iOiIwLjAwMDIwNTY3MzY5NTEyNTkxODYiLCJpYXQiOjE3NDE3MjY5MTUsImV4cCI6MTc0MjMzMTcxNX0.0KO5kFgOH73UNVFMS6nsXcC0x35BXiLJyHKy2jQ29zU"
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NkODFhYmIzZDY4NmNkZWYxYzhhZTYiLCJyYW5kb20iOiIwLjQyNDY2Nzk5ODI0NzIzMjM0IiwiaWF0IjoxNzQxNTQ1NzExLCJleHAiOjE3NDIxNTA1MTF9.LrO9zZ7j5PxgNv-wEdpjlS-Z5gtMg2MzkgTD2onxrqI"
}


### Delete User

DELETE http://localhost:3000/users/67c5db63ea35896fccde5f7d
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1ZGI2M2VhMzU4OTZmY2NkZTVmN2QiLCJyYW5kb20iOiIwLjE5NTIzMTQ2NTMxNTgwNDI2IiwiaWF0IjoxNzQxMDIwMDU4LCJleHAiOjE3NDE2MjQ4NTh9.wuhYxqSRgcKwE42s5vBX7VJAg5oAq6wbXZSDXG4AD4o

### Get User By Id
GET http://localhost:3000/users/67c5cf8f686af915f4ca5ef6
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1Y2Y4ZjY4NmFmOTE1ZjRjYTVlZjYiLCJyYW5kb20iOiIwLjIyNDY1NTA2NzQ2ODk3NzEyIiwiaWF0IjoxNzQxMDE3MDcyLCJleHAiOjE3NDE2MjE4NzJ9.2Pvu-yHtdl117T5c2GJFLzyzJOVpJ_uNitgt8bzbtV4


### Get All Users

GET http://localhost:3000/users
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1Y2Y4ZjY4NmFmOTE1ZjRjYTVlZjYiLCJyYW5kb20iOiIwLjIyNDY1NTA2NzQ2ODk3NzEyIiwiaWF0IjoxNzQxMDE3MDcyLCJleHAiOjE3NDE2MjE4NzJ9.2Pvu-yHtdl117T5c2GJFLzyzJOVpJ_uNitgt8bzbtV4

### Get User By Id
GET http://localhost:3000/users/67c5cf8f686af915f4ca5ef6
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1Y2Y4ZjY4NmFmOTE1ZjRjYTVlZjYiLCJyYW5kb20iOiIwLjIyNDY1NTA2NzQ2ODk3NzEyIiwiaWF0IjoxNzQxMDE3MDcyLCJleHAiOjE3NDE2MjE4NzJ9.2Pvu-yHtdl117T5c2GJFLzyzJOVpJ_uNitgt8bzbtV4


### Update User

PUT http://localhost:3000/users/67c5cf8f686af915f4ca5ef6
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M1Y2Y4ZjY4NmFmOTE1ZjRjYTVlZjYiLCJyYW5kb20iOiIwLjIyNDY1NTA2NzQ2ODk3NzEyIiwiaWF0IjoxNzQxMDE3MDcyLCJleHAiOjE3NDE2MjE4NzJ9.2Pvu-yHtdl117T5c2GJFLzyzJOVpJ_uNitgt8bzbtV4
Content-Type: application/json

{
  "email": "yaeli@gmail",
  "password": "ssss"
}



### Create like
POST http://localhost:3000/likes
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA
Content-Type: application/json

{
  "postId": "67cc84d1f5d54670427842c9"
}

### Delete like
DELETE http://localhost:3000/likes/67cc84d1f5d54670427842c9
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NjODQ4NWY1ZDU0NjcwNDI3ODQyYzUiLCJyYW5kb20iOiIwLjc2MDI5NzQ2MjU0MDMyMzgiLCJpYXQiOjE3NDE0NTY1MjQsImV4cCI6MTc0MjA2MTMyNH0.8yuKXTWS8OpROk6YMYsmZTpLPpkSs0ecOpf9tUHeUlA


### Google Register

POST http://localhost:3000/auth/google
Content-Type: application/json

{
  "credential": "mock_google_token"
}

### Get First Page of Posts (10 per page)
GET http://localhost:3000/posts/paging?page=2
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NmMGYyNDQxODYxNGM4NDljOTc0MzEiLCJyYW5kb20iOiIwLjE2NDQxNjAzOTQ3NjQ3MTU0IiwiaWF0IjoxNzQxNjIzMTYzLCJleHAiOjE3NDIyMjc5NjN9.lJF-5WRV41hf0xV3UcKKbHvxyyO5lFS_u8bWjRVTdjo


### Get Second Page of Posts
GET http://localhost:3000/posts/paging?sender=67cd81abb3d686cdef1c8ae6&page=4
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NmMGYyNDQxODYxNGM4NDljOTc0MzEiLCJyYW5kb20iOiIwLjE2NDQxNjAzOTQ3NjQ3MTU0IiwiaWF0IjoxNzQxNjIzMTYzLCJleHAiOjE3NDIyMjc5NjN9.lJF-5WRV41hf0xV3UcKKbHvxyyO5lFS_u8bWjRVTdjo
